FROM python:3.7

MAINTAINER Klochkov Yarolsav <klochkovy18@gmail.com>

ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD offers/ /code/
WORKDIR /code/offers/src
